#!/bin/bash
:<<EOF
simple test file for riscv 
big homework
EOF
RED='\E[1;31m'
GRN='\E[1;32m'
GOD='\E[1;33m'
NON='\E[1;0m'
score=0
for file in $(ls src/ | grep data)
do
		cfile=${file//data/c}
		cd src/
		g++ $cfile
		./a.out
		ans=$?
		rm a.out
		cd ..
		myans=$(./cmake-build-debug/code < "./src/$file")
		#echo -e "Test for ${file//.data}\c"
		if [[ $ans -eq $myans ]]
		then 
				echo -e "${NON}${RES}\c"
				printf "Test for %-20s" ${file//.data}
				echo -e "${GRN}AC${RES}"
				score=$((score+10))
		else
				echo -e "${NON}${RES}\c"
				printf "Test for %-20s" ${file//.data}
				echo -e "${RED}WA${RES}"
		fi
done
echo -e "${GOD}Congradulations! You got $score/180 score.${RES}"
