#!/bin/bash

for file in $(ls src/ | grep .data )
do
	cfile=${file//data/c}
	cd src/
    g++ $cfile
    ./a.out
	ans=$?
	cd ..
	myans=$(./cmake-build-debug/code < ./src/$file)
	if [ $ans -eq $myans ]
	then echo "AC"
	else
			echo "WA"
	fi
done

		
